channels:
  - conda-forge
  - pytorch
  - bioconda

dependencies:
  - jupyter_contrib_nbextensions==0.5.1
  - jupyterhub-base==2.3.1
  - jupyterhub-singleuser=2.3.1
  - numpy
  - matplotlib
  - scipy
  - pandas
  - tqdm
  - s3fs
  - awscli
  - scikit-learn
  - datalad
  - datalad-container
  - singularity
  - altair
  - seaborn
  - graphviz
  - pygraphviz
  - python-graphviz
  - jax
  - numba
  - cython
  - pytorch==2.3.1
  - torchvision==0.18
  - pytorch::cpuonly
  - dcm2niix
  - openneuro-py
  - ipyvolume
  - nodejs
  - pymvpa
  - s5cmd
  - imbalanced-learn
  - tensorflow
  - nitime
  - statsmodels
  - openneuro-py
  - pip:
    - best-toolbox
    - nbgitpuller
    - pymef
    - pybids
    - nipype
    - neuropythy>=0.12.15
    - dipy
    - mne
    - nilearn
    - dask[complete]
    - nimare
    - osfclient
    - line_profiler
    - memory_profiler
    - black
    - mne_bids
    - ipympl
    - pyfftw
    - pliers
    - duecredit
    - git-credential-helpers
    - cloudpathlib[s3,gz,azure]
    - colorspacious
    - requests
    - platformdirs
    - git+https://github.com/kjamison/krakencoder.git@571c77f12266ee8685222399e5eee80c8a4cdea7
    - git+https://github.com/rmarkello/abagen.git@dc4a007
